### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ForgedChemist** [ForgedChemist/HWTEST2#1]
- [x] change the app.py so it doesn't reset the database everytime it restarts (complicated)
- [x] make the how it works and about us parts of the entry page.
- [x] change footer content.
- [x] add our logo to the tab part
